name: Deploy index.html to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'   # triggers only when this file changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload website folder
        uses: actions/upload-pages-artifact@v1
        with:
          path: index.html         # folder containing index.html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1

